# Generated by Django 3.2.5 on 2021-09-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

   

    operations = [
        migrations.CreateModel(
            name='NoticiaTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),                               
                ('title', models.TextField(blank=True, null=True)),
                ('subtitulo', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'noticia_tb',
                'managed': False,
            },
        ),
       
    ]
